import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Passer de 1 à plusieurs tractions : progresser sans tester son max",
  description: "Tu sais faire une traction mais pas encore plusieurs ? Apprends à accumuler des répétitions propres, régler la difficulté et construire progressivement ton volume.",
  alternates: { canonical: "/bibliotheque/10-tractions/" },
  openGraph: { title: "De 1 à plusieurs tractions : construire du volume", description: "Une progression pratique après ta première traction, sans promesse de délai ni test maximal permanent.", type: "article", url: "/bibliotheque/10-tractions/" },
};

export default function MorePullUpsPage() {
  return <>
    <section className="hero shell"><div className="heroGrid"><div><div className="eyebrow">Tractions · après la première répétition</div><h1>Tu sais faire une traction. Maintenant, apprends à en construire plusieurs.</h1><p className="lead">La première traction change le problème : tu n'as plus besoin de prouver que le mouvement est possible. Tu dois maintenant accumuler assez de répétitions de qualité pour rendre cette capacité reproductible.</p></div><aside className="manifesto"><span>Idée centrale</span><strong>Ton maximum n'est pas ton programme.</strong><p>Si chaque séance consiste à vérifier combien de tractions tu peux faire jusqu'à l'échec, tu mesures souvent ta fatigue autant que ta progression.</p></aside></div></section>

    <section className="section sectionSoft"><div className="shell"><div className="sectionHeading wide"><div className="eyebrow">Réponse rapide</div><h2>Comment passer de 1 traction à plusieurs ?</h2><p>Garde ta traction stricte comme mouvement de référence, mais pratique surtout des répétitions que tu peux encore reproduire proprement. Quand une série devient trop difficile, continue le travail avec une assistance ou une variante plus facile plutôt que de transformer chaque répétition en tentative maximale.</p></div><div className="cardGrid"><article className="plainCard"><h3>Si tu n'as qu'une répétition</h3><p>Une seule traction peut déjà être pratiquée plusieurs fois séparément avec assez de récupération. L'objectif est d'accumuler de bonnes expositions au mouvement, pas de forcer immédiatement une deuxième répétition dégradée.</p></article><article className="plainCard"><h3>Si tu en fais 2 à 4</h3><p>Travaille souvent en dessous de ton maximum. Plusieurs petites séries propres donnent davantage d'occasions de pratiquer une technique stable qu'une seule série poussée jusqu'à l'échec.</p></article><article className="plainCard"><h3>Si la qualité chute vite</h3><p>Allonge la récupération, réduis le nombre de répétitions par série ou termine avec une assistance. Une répétition supplémentaire n'est pas utile si elle change complètement le mouvement.</p></article></div></div></section>

    <section className="section shell"><div className="sectionHeading"><div className="eyebrow">Ce que tu dois observer</div><h2>La progression apparaît avant le chiffre final.</h2></div><div className="cardGrid"><article className="plainCard"><h3>Répétabilité</h3><p>Ta première répétition et les suivantes se ressemblent davantage : même amplitude utile, moins d'élan, trajectoire plus stable.</p></article><article className="plainCard"><h3>Réserve</h3><p>Une répétition qui demandait tout ton effort devient moins coûteuse. Tu peux récupérer puis la reproduire sans sensation de tentative exceptionnelle.</p></article><article className="plainCard"><h3>Volume de qualité</h3><p>Tu peux réaliser davantage de répétitions propres sur l'ensemble d'une séance, même si ton record sur une seule série n'a pas encore bougé.</p></article></div></section>

    <section className="section sectionSoft"><div className="shell"><div className="sectionHeading wide"><div className="eyebrow">À éviter</div><h2>Trois pièges fréquents après la première traction.</h2></div><div className="cardGrid"><article className="plainCard"><h3>Tester son maximum tout le temps</h3><p>Un test sert à mesurer. Il n'a pas besoin de devenir la totalité de l'entraînement.</p></article><article className="plainCard"><h3>Compter des répétitions différentes</h3><p>Si l'amplitude raccourcit et que le balancement augmente à chaque répétition, le chiffre monte plus vite que la capacité réelle.</p></article><article className="plainCard"><h3>Copier un délai universel</h3><p>Les recherches et forums montrent des progressions très différentes d'une personne à l'autre. Calis ne promet donc ni « 5 tractions en X semaines » ni « 10 en un mois ».</p></article></div></div></section>

    <section className="section shell"><div className="sectionHeading"><div className="eyebrow">Choisir la suite</div><h2>Ton prochain objectif dépend de ce que tu veux développer.</h2></div><div className="choiceList"><Link className="choice" href="/bibliotheque/traction-technique"><span>Mes répétitions sont irrégulières : stabiliser ma technique</span><span>→</span></Link><Link className="choice" href="/bibliotheque/traction-assistee"><span>Je manque vite de volume : utiliser une assistance intelligemment</span><span>→</span></Link><Link className="choice" href="/bibliotheque/traction-explosive"><span>Mon socle est solide : développer hauteur et vitesse</span><span>→</span></Link><Link className="choice" href="/bibliotheque/tractions-lestees"><span>Mon socle est solide : développer davantage de force</span><span>→</span></Link><Link className="choice" href="/tractions"><span>Revenir au parcours complet des tractions</span><span>→</span></Link></div></section>
  </>;
}
