import type { ProgressionStep, Resource } from "./types";

export const v1Resources: Resource[] = [
  { slug: "par-ou-commencer-calisthenie", title: "Par où commencer en callisthénie ?", summary: "Un point d'entrée simple pour comprendre quoi travailler quand on part de zéro.", level: "zero", kind: "guide", capability: "mouvement", hub: "commencer", equipment: [], next: ["premiere-pompe", "premiere-traction", "squat-poids-du-corps", "mobilite-debutant"] },
  { slug: "squat-poids-du-corps", title: "Squat au poids du corps : construire sa base", summary: "Apprendre à s'accroupir avec une amplitude contrôlée et adaptée à sa mobilité actuelle.", level: "zero", kind: "exercise", capability: "jambes", hub: "commencer", equipment: [], next: ["mobilite-debutant"] },
  { slug: "mobilite-debutant", title: "Mobilité pour débuter : quoi travailler vraiment ?", summary: "Explorer les amplitudes utiles sans chercher à devenir souple partout avant de commencer.", level: "zero", kind: "guide", capability: "mouvement", hub: "commencer", equipment: [], next: ["squat-poids-du-corps", "poignets-handstand"] },
  { slug: "premiere-pompe", title: "Réussir sa première pompe", summary: "Évaluer son niveau, choisir une régression et progresser jusqu'à une pompe contrôlée.", level: "zero", kind: "progression", capability: "pousser", hub: "pompes", equipment: [], next: ["pompe-technique"] },
  { slug: "pourquoi-je-narrive-pas-a-faire-une-pompe", title: "Pourquoi je n'arrive pas à faire une pompe ?", summary: "Identifier si le sol est simplement trop difficile, si le mouvement se désorganise, si les appuis limitent ou si une régression est nécessaire.", level: "zero", kind: "question", capability: "pousser", hub: "pompes", equipment: [], next: ["pompes-inclinees", "premiere-pompe"] },
  { slug: "premiere-traction", title: "Réussir sa première traction", summary: "Construire suspension, contrôle scapulaire et force de tirage avant la première répétition stricte.", level: "zero", kind: "progression", capability: "tirer", hub: "tractions", equipment: ["barre"], next: ["traction-technique", "10-tractions"] },
  { slug: "pourquoi-je-narrive-pas-a-faire-une-traction", title: "Pourquoi je n'arrive pas à faire une traction ?", summary: "Identifier si le blocage vient de la suspension, du contrôle des épaules, de la force de tirage, de l'assistance ou de la descente.", level: "zero", kind: "question", capability: "tirer", hub: "tractions", equipment: ["barre"], next: ["premiere-traction"] },
  { slug: "traction-technique", title: "Traction : technique et repères", summary: "Comprendre le mouvement, les prises, l'amplitude et les sensations utiles.", level: "beginner", kind: "exercise", capability: "tirer", hub: "tractions", equipment: ["barre"], next: ["10-tractions"] },
  { slug: "suspension-barre", title: "Apprendre à se suspendre à une barre", summary: "Construire une suspension confortable et contrôlée avant de tirer.", level: "zero", kind: "exercise", capability: "tirer", hub: "tractions", equipment: ["barre"], next: ["controle-scapulaire"] },
  { slug: "controle-scapulaire", title: "Contrôle scapulaire en suspension", summary: "Apprendre à engager et déplacer les omoplates avant les tractions complètes.", level: "beginner", kind: "exercise", capability: "tirer", hub: "tractions", equipment: ["barre"], next: ["rowing-incline"] },
  { slug: "rowing-incline", title: "Rowing incliné au poids du corps", summary: "Développer le tirage horizontal avec une difficulté ajustable.", level: "beginner", kind: "exercise", capability: "tirer", hub: "tractions", equipment: ["barre-basse-ou-anneaux"], next: ["traction-assistee"] },
  { slug: "traction-assistee", title: "Traction assistée : comment bien l'utiliser", summary: "Utiliser assistance ou élastique sans masquer les faiblesses techniques.", level: "beginner", kind: "exercise", capability: "tirer", hub: "tractions", equipment: ["barre", "elastique-facultatif"], next: ["traction-negative"] },
  { slug: "quelle-bande-elastique-tractions", title: "Quelle bande élastique choisir pour les tractions ?", summary: "Choisir une assistance adaptée au mouvement réel plutôt qu'une couleur ou un nombre de kilos pris comme règle universelle.", level: "beginner", kind: "equipment", capability: "tirer", hub: "tractions", equipment: ["barre", "elastique-facultatif"], next: ["traction-assistee"] },
  { slug: "traction-negative", title: "Traction négative", summary: "Développer le contrôle excentrique pour se rapprocher de la traction stricte.", level: "beginner", kind: "exercise", capability: "tirer", hub: "tractions", equipment: ["barre"], next: ["premiere-traction"] },
  { slug: "10-tractions", title: "Passer de 1 à plusieurs tractions", summary: "Organiser volume, régularité et qualité pour construire plusieurs répétitions fiables sans transformer chaque séance en test maximal.", level: "beginner", kind: "program", capability: "force", hub: "tractions", equipment: ["barre"], next: ["traction-explosive", "tractions-lestees"] },
  { slug: "traction-explosive", title: "Développer la traction explosive", summary: "Transformer la force de tirage en hauteur et vitesse avant le muscle-up.", level: "intermediate", kind: "progression", capability: "tirer", hub: "tractions", equipment: ["barre"], next: ["transition-muscle-up", "pourquoi-je-narrive-pas-a-faire-un-muscle-up"] },
  { slug: "tractions-lestees", title: "Commencer les tractions lestées", summary: "Savoir quand ajouter du poids et comment progresser sans brûler les étapes.", level: "intermediate", kind: "guide", capability: "force", hub: "tractions", equipment: ["barre", "ceinture-de-lest-facultative"] },
  { slug: "pourquoi-je-narrive-pas-a-faire-un-muscle-up", title: "Pourquoi je n'arrive pas à faire un muscle-up ?", summary: "Identifier si le blocage vient de la base de traction, de la hauteur de tirage, de la transition, d'une asymétrie ou de la poussée au-dessus de la barre.", level: "intermediate", kind: "question", capability: "tirer", hub: "muscle-up", equipment: ["barre"], next: ["traction-explosive", "transition-muscle-up", "dips-technique"] },
  { slug: "transition-muscle-up", title: "Transition muscle-up : passer au-dessus de la barre", summary: "Apprendre à relier un tirage suffisamment haut à l'appui au-dessus de la barre dans une situation contrôlable.", level: "intermediate", kind: "progression", capability: "mouvement", hub: "muscle-up", equipment: ["barre"], next: ["dips-technique"] },
  { slug: "pompe-technique", title: "Pompe : technique et repères", summary: "Alignement, amplitude, gainage et position des mains pour une pompe contrôlée.", level: "beginner", kind: "exercise", capability: "pousser", hub: "pompes", equipment: [] },
  { slug: "pompes-inclinees", title: "Pompes inclinées : régler la difficulté", summary: "Utiliser la hauteur d'un support stable pour construire une vraie poussée et progresser graduellement vers le sol.", level: "zero", kind: "exercise", capability: "pousser", hub: "pompes", equipment: ["support"] },
  { slug: "dips-debutant", title: "Premiers dips", summary: "Construire stabilité et force de poussée avant les dips complets.", level: "beginner", kind: "progression", capability: "pousser", hub: "dips", equipment: ["barres-paralleles"] },
  { slug: "dips-technique", title: "Dips : technique et erreurs fréquentes", summary: "Comprendre amplitude, trajectoire et contrôle des épaules.", level: "beginner", kind: "exercise", capability: "pousser", hub: "dips", equipment: ["barres-paralleles"] },
  { slug: "handstand-debutant", title: "Commencer le handstand", summary: "Construire appuis, ligne et sécurité avant de chercher l'équilibre libre.", level: "beginner", kind: "progression", capability: "equilibre", hub: "handstand", equipment: ["mur-facultatif"], next: ["poignets-handstand", "handstand-mur"] },
  { slug: "handstand-mur", title: "Handstand au mur", summary: "Utiliser le mur pour apprendre l'alignement sans dépendre de l'élan.", level: "beginner", kind: "exercise", capability: "equilibre", hub: "handstand", equipment: ["mur"], next: ["premiers-equilibres-handstand"] },
  { slug: "poignets-handstand", title: "Préparer ses poignets au handstand", summary: "Mobilité, charge progressive et repères de tolérance avant les appuis prolongés.", level: "beginner", kind: "guide", capability: "mouvement", hub: "handstand", equipment: [], next: ["handstand-mur"] },
  { slug: "premiers-equilibres-handstand", title: "Premiers équilibres libres en handstand", summary: "Réduire progressivement l'aide du mur et apprendre à utiliser la pression des mains pour corriger de petits déséquilibres.", level: "beginner", kind: "progression", capability: "equilibre", hub: "handstand", equipment: ["mur-facultatif"] },
  { slug: "parallettes-handstand", title: "Parallettes pour le handstand : utiles ou non ?", summary: "Comprendre quand les parallettes changent réellement le confort ou la progression.", level: "beginner", kind: "equipment", capability: "equilibre", hub: "handstand", equipment: ["parallettes-facultatives"] }
];

export const pullUpProgression: ProgressionStep[] = [
  { id: "hang", label: "Suspension", resourceSlug: "suspension-barre", criterion: "Se suspendre confortablement et garder une prise stable." },
  { id: "scapula", label: "Contrôle scapulaire", resourceSlug: "controle-scapulaire", criterion: "Déplacer les omoplates sans plier fortement les coudes." },
  { id: "row", label: "Rowing incliné", resourceSlug: "rowing-incline", criterion: "Réaliser des répétitions propres avec un angle adapté." },
  { id: "assist", label: "Traction assistée", resourceSlug: "traction-assistee", criterion: "Conserver une trajectoire et une amplitude cohérentes." },
  { id: "negative", label: "Négatives", resourceSlug: "traction-negative", criterion: "Contrôler la descente sans chute rapide." },
  { id: "first", label: "Première traction", resourceSlug: "premiere-traction", criterion: "Réaliser une répétition stricte et reproductible." },
  { id: "ten", label: "Plusieurs tractions", resourceSlug: "10-tractions", criterion: "Construire plusieurs répétitions fiables avant les objectifs plus avancés." }
];

export const pushUpProgression: ProgressionStep[] = [
  { id: "incline", label: "Pompes inclinées", resourceSlug: "pompes-inclinees", criterion: "Trouver une hauteur où la descente et la remontée restent contrôlées." },
  { id: "first-pushup", label: "Première pompe", resourceSlug: "premiere-pompe", criterion: "Réaliser une répétition au sol contrôlée et reproductible." },
  { id: "pushup-technique", label: "Pompe stable", resourceSlug: "pompe-technique", criterion: "Garder des repères comparables sur plusieurs répétitions avant de chercher plus difficile." }
];

export const handstandProgression: ProgressionStep[] = [
  { id: "wrists", label: "Préparer les appuis", resourceSlug: "poignets-handstand", criterion: "Tolérer progressivement la charge sur les mains sans douleur vive ni réaction inhabituelle." },
  { id: "wall", label: "Handstand au mur", resourceSlug: "handstand-mur", criterion: "Entrer, rester calme, réduire le contact avec le mur et sortir volontairement." },
  { id: "free-balance", label: "Premiers équilibres", resourceSlug: "premiers-equilibres-handstand", criterion: "Créer de courts instants sans aide où les mains commencent à corriger de petits déséquilibres." }
];
