import { notFound } from "next/navigation";
import Link from "next/link";
import { v1Resources } from "@/lib/content/v1";

export function generateStaticParams() {
  return v1Resources.map((resource) => ({ slug: resource.slug }));
}

type LearningCard = {
  intro: string;
  objective: string;
  test: string;
  technique: string[];
  feel: string[];
  avoid: string[];
  advance: string;
  next?: { slug: string; label: string };
  secondaryNext?: { slug: string; label: string };
};

const cards: Record<string, LearningCard> = {
  "suspension-barre": { intro: "Avant de tirer ton corps vers la barre, apprends à y rester. La suspension construit la prise et les premiers repères autour des épaules.", objective: "Une suspension calme, stable et reproductible.", test: "Accroche-toi avec une prise confortable. Si tes mains lâchent immédiatement ou si tu te crispes fortement, commence par des expositions courtes et contrôlées.", technique: ["Utilise une prise complète et confortable.", "Laisse les bras s'allonger sans rechercher un relâchement douloureux.", "Garde le corps calme sans créer d'élan.", "Descends avant de perdre complètement le contrôle de la prise."], feel: ["Les mains et avant-bras travaillent.", "Le corps devient plus calme sous la barre.", "La position devient progressivement familière."], avoid: ["Douleur vive à l'épaule, au coude ou au poignet.", "Glissement incontrôlé des mains.", "Balancement volontaire pour simplement tenir."], advance: "Passe au contrôle scapulaire lorsque tu peux te suspendre avec assez de marge pour penser à tes épaules, pas seulement à ta prise.", next: { slug: "controle-scapulaire", label: "Apprendre le contrôle scapulaire" } },
  "controle-scapulaire": { intro: "La traction ne commence pas uniquement en pliant les coudes. Apprends à reconnaître et contrôler le mouvement des omoplates.", objective: "Initier un petit mouvement contrôlé avec les coudes presque tendus.", test: "Depuis une suspension stable, modifie légèrement la position des épaules sans tirer avec les bras. Si les coudes plient immédiatement, réduis l'amplitude.", technique: ["Pars d'une suspension stable.", "Déplace épaules et omoplates avec une faible amplitude.", "Cherche du contrôle plutôt qu'une posture figée.", "Reviens lentement au départ."], feel: ["Le haut du dos participe.", "Le corps monte légèrement sans gros mouvement des coudes.", "Le retour reste contrôlé."], avoid: ["Hausser brutalement les épaules.", "Transformer chaque répétition en demi-traction.", "Forcer une amplitude douloureuse."], advance: "Passe au rowing quand ce petit mouvement est reproductible sans élan.", next: { slug: "rowing-incline", label: "Construire le tirage avec le rowing" } },
  "rowing-incline": { intro: "Le rowing incliné apprend à tirer son corps avec une difficulté très facilement ajustable.", objective: "Développer un tirage propre et progressivement plus exigeant.", test: "Choisis un angle où tu peux tirer sans perdre l'alignement. Si tout devient chaotique, rends ton corps plus vertical.", technique: ["Garde le corps organisé de la tête aux pieds.", "Tire la poitrine vers le support.", "Contrôle aussi le retour.", "Modifie l'inclinaison pour ajuster la difficulté."], feel: ["Dos et bras tirent ensemble.", "Le tronc stabilise le corps.", "La difficulté augmente quand le corps devient plus horizontal."], avoid: ["Donner un coup de bassin.", "Raccourcir progressivement l'amplitude.", "Choisir un angle qui détruit la répétabilité."], advance: "Passe à une traction assistée lorsque ton rowing reste propre à une inclinaison exigeante.", next: { slug: "traction-assistee", label: "Passer à la traction assistée" } },
  "traction-assistee": { intro: "L'assistance permet de pratiquer le vrai mouvement avant de déplacer seul tout son poids.", objective: "Répéter une traction complète avec une aide progressivement réduite.", test: "Choisis une assistance qui permet l'amplitude sans te projeter vers le haut.", technique: ["Pars sans balancement volontaire.", "Laisse l'aide assister sans dicter la trajectoire.", "Monte et redescends avec contrôle.", "Réduis progressivement l'assistance."], feel: ["Tu produis encore un effort important.", "La trajectoire ressemble à une traction libre.", "Le point difficile reste perceptible."], avoid: ["Une bande qui fait presque tout le travail.", "Une amplitude dictée par l'élastique.", "Accumuler des répétitions rapides sans contrôle."], advance: "Passe davantage de temps sur les négatives quand l'assistance est devenue modérée et le retour bien contrôlé.", next: { slug: "traction-negative", label: "Renforcer la descente" } },
  "traction-negative": { intro: "La négative commence en haut et développe la capacité à contrôler toute la descente.", objective: "Descendre sur toute l'amplitude sans chute brutale.", test: "Place-toi en haut avec un support stable. Si tu tombes immédiatement, ajoute de l'aide ou raccourcis la portion contrôlée.", technique: ["Installe-toi proprement en position haute.", "Descends aussi régulièrement que possible.", "Garde épaules, bras et tronc organisés.", "Arrête lorsque la descente n'est plus contrôlée."], feel: ["Forte tension dans dos et bras.", "Effort variable selon l'angle.", "Fatigue musculaire importante avec peu de répétitions."], avoid: ["Tomber brutalement en bas.", "Accumuler beaucoup de négatives très fatigué.", "Ignorer une douleur articulaire."], advance: "Teste une traction stricte lorsque les descentes sont reproductibles et que ton assistance a nettement diminué.", next: { slug: "premiere-traction", label: "Tenter ta première traction" } },
  "traction-technique": { intro: "Une traction stricte est un mouvement contrôlé entre une position basse stable et une position haute nette.", objective: "Une répétition complète, contrôlée et reproductible.", test: "Filme une répétition confortable et vérifie si départ, montée et descente restent cohérents sans balancement marqué.", technique: ["Pars d'une suspension contrôlée.", "Tire en gardant le corps organisé.", "Atteins une position haute claire sans projeter la tête.", "Redescends avec le même contrôle."], feel: ["Dos et bras travaillent ensemble.", "Le tronc limite les oscillations.", "La dernière répétition ressemble encore à la première."], avoid: ["Kipping involontaire.", "Amplitude qui raccourcit avec la fatigue.", "Prise ou trajectoire douloureuse."], advance: "Quand ta traction est reproductible, commence à construire du volume.", next: { slug: "10-tractions", label: "Construire de 1 à 10 tractions" } },
  "10-tractions": { intro: "Passer d'une traction à plusieurs demande surtout d'accumuler des répétitions de qualité plutôt que de tester son maximum chaque jour.", objective: "Augmenter le volume sans sacrifier la forme.", test: "Fais une série confortable sans aller volontairement à l'échec et observe quand la technique commence à changer.", technique: ["Garde une marge sur la majorité des séries.", "Accumule plusieurs petites séries propres si nécessaire.", "Conserve les exercices qui corrigent ton maillon faible.", "Augmente une variable à la fois."], feel: ["Fatigue musculaire progressive et contrôlable.", "Répétitions encore reconnaissables en fin de séance.", "Bonne qualité retrouvée à la séance suivante."], avoid: ["Tester le maximum à chaque séance.", "Ajouter du volume avec une amplitude dégradée.", "Ignorer une baisse durable ou une douleur croissante."], advance: "Quand dix tractions propres deviennent un repère réaliste, choisis entre vitesse/hauteur et force lestée.", next: { slug: "traction-explosive", label: "Développer la traction explosive" }, secondaryNext: { slug: "tractions-lestees", label: "Commencer les tractions lestées" } },
  "traction-explosive": { intro: "La traction explosive transforme la force de tirage en vitesse et en hauteur.", objective: "Monter plus haut sans remplacer la force par du balancement.", test: "Observe jusqu'où monte naturellement ta poitrine lorsque tu tires vite sur une répétition fraîche.", technique: ["Travaille suffisamment frais.", "Accélère dès le début du tirage.", "Garde peu de répétitions pour préserver la vitesse.", "Conserve parallèlement des tractions strictes."], feel: ["Accélération franche.", "Tirage plus haut sans grand élan des jambes.", "Intention de vitesse nette."], avoid: ["Confondre explosivité et balancement.", "Continuer lorsque la vitesse s'effondre.", "Chercher la hauteur avec une articulation douloureuse."], advance: "Une hauteur de tirage croissante et contrôlée prépare notamment le futur parcours muscle-up." },
  "tractions-lestees": { intro: "Le lest est utile quand la traction au poids du corps est déjà stable et que l'objectif devient davantage la force.", objective: "Ajouter une résistance mesurable sans perdre la répétition de référence.", test: "Avant d'ajouter du poids, vérifie que tes tractions au poids du corps restent régulières et contrôlées.", technique: ["Commence avec une charge modeste.", "Garde la même amplitude qu'au poids du corps.", "Progresse par petites augmentations.", "Conserve du travail sans lest."], feel: ["Même mouvement, effort plus élevé.", "Tronc plus sollicité pour stabiliser la charge.", "Technique encore reconnaissable."], avoid: ["Lester une traction déjà instable.", "Augmenter le poids à chaque séance par principe.", "Laisser la charge se balancer fortement."], advance: "Continue tant que la charge augmente sans détériorer durablement la technique ; une programmation plus spécialisée viendra plus tard." },

  "pompes-inclinees": { intro: "La pompe inclinée réduit la part de ton poids à pousser tout en conservant le mouvement général d'une pompe. C'est une régression simple, mesurable et accessible.", objective: "Réaliser des pompes contrôlées sur un support stable puis abaisser progressivement ce support.", test: "Choisis une surface solide à une hauteur où tu peux descendre et remonter sans casser immédiatement l'alignement du corps.", technique: ["Pose les mains sur un support réellement stable.", "Garde tête, tronc et bassin organisés ensemble.", "Descends la poitrine vers le support avec les coudes qui suivent une trajectoire confortable.", "Quand le mouvement devient facile et répétable, utilise un support légèrement plus bas."], feel: ["Poitrine, triceps et épaules participent ensemble.", "Le tronc empêche le bassin de s'affaisser.", "La difficulté augmente progressivement quand le support descend."], avoid: ["Support glissant ou instable.", "Bassin qui reste en arrière pendant que seule la poitrine avance.", "Descendre plus bas malgré une douleur nette à l'épaule ou au poignet."], advance: "Passe à la pompe au sol quand une faible inclinaison te permet encore de garder une répétition calme et complète.", next: { slug: "premiere-pompe", label: "Tenter ta première pompe au sol" } },
  "pompe-technique": { intro: "La bonne pompe n'est pas une silhouette parfaite imposée à tout le monde : c'est une poussée stable où les mains, les épaules et le tronc coopèrent sur une amplitude que tu contrôles.", objective: "Construire une pompe reproductible du haut vers le bas puis retour.", test: "Filme quelques répétitions de profil. Observe surtout si ton bassin s'effondre, si ta tête part seule vers le sol ou si l'amplitude change à chaque répétition.", technique: ["Place les mains dans une largeur confortable plutôt que de chercher une mesure universelle.", "Organise le tronc avant de descendre pour que poitrine et bassin se déplacent ensemble.", "Laisse les coudes suivre une trajectoire naturelle plutôt que de les forcer complètement contre le corps ou à 90 degrés.", "Pousse le sol jusqu'à retrouver une position haute stable."], feel: ["Poitrine, triceps et avant d'épaule travaillent.", "Abdominaux et fessiers participent à l'alignement.", "La pression reste répartie dans les mains."], avoid: ["Douleur vive au poignet, coude ou épaule.", "Bassin qui tombe nettement avant la poitrine.", "Amplitude de plus en plus courte pour sauver les répétitions."], advance: "Quand tes pompes sont régulières, tu peux augmenter progressivement le volume ou passer vers une poussée plus exigeante comme les dips selon ton objectif.", next: { slug: "dips-debutant", label: "Découvrir le parcours dips" } },
  "dips-debutant": { intro: "Les dips demandent davantage de charge aux épaules et aux bras qu'une pompe classique. Avant de chercher de la profondeur, apprends à supporter ton poids entre deux barres et à contrôler une petite amplitude.", objective: "Construire un appui stable puis un dip avec une amplitude confortable et maîtrisée.", test: "Sur des barres parallèles stables, prends un appui bras tendus. Si tu ne peux pas maintenir la position sans douleur ni perte immédiate de contrôle, reste sur le travail d'appui et de poussée plus accessible.", technique: ["Commence par un appui haut stable, épaules et tronc contrôlés.", "Descends progressivement plutôt que de chercher tout de suite une grande profondeur.", "Laisse le buste adopter une inclinaison naturelle sans effondrer les épaules.", "Pousse les barres pour revenir à une position haute nette."], feel: ["Triceps, poitrine et épaules travaillent fortement.", "Le tronc stabilise le corps entre les barres.", "L'amplitude reste sous ton contrôle."], avoid: ["Tomber rapidement dans le bas du dip.", "Chercher une profondeur maximale malgré une gêne antérieure d'épaule.", "Balancer les jambes pour sortir du point difficile."], advance: "Passe à la fiche technique lorsque tu peux réaliser des répétitions contrôlées sur une amplitude confortable et reproductible.", next: { slug: "dips-technique", label: "Affiner la technique des dips" } },
  "dips-technique": { intro: "La profondeur et l'inclinaison d'un dip ne sont pas des concours. La priorité est une trajectoire que tes épaules tolèrent et que tu peux reproduire sans rebond.", objective: "Rendre le dip stable, contrôlé et adapté à ta mobilité.", test: "Observe une série de profil : repère l'endroit où le contrôle diminue, où les épaules deviennent inconfortables ou où tu dois rebondir pour remonter.", technique: ["Pars d'un appui haut stable.", "Descends avec une vitesse maîtrisée.", "Choisis une profondeur que tu peux contrôler et tolérer.", "Remonte sans coup de jambes et stabilise le haut avant la répétition suivante."], feel: ["Forte poussée des bras et de la poitrine.", "Épaules chargées mais sans douleur vive.", "Trajectoire similaire d'une répétition à l'autre."], avoid: ["Rebond en bas.", "Profondeur imposée malgré une gêne.", "Épaules qui perdent brutalement leur contrôle sous fatigue."], advance: "Quand le dip est solide, augmente le volume ou la difficulté progressivement ; le lest n'a d'intérêt que lorsque le mouvement de base est déjà fiable." },
  "poignets-handstand": { intro: "Le handstand place beaucoup plus de charge sur les mains qu'une journée ordinaire. Les poignets ont surtout besoin d'une exposition progressive, pas d'un rituel magique.", objective: "Tolérer progressivement l'appui sur les mains dans plusieurs angles confortables.", test: "Au sol, place les mains à plat puis transfère doucement une partie du poids vers l'avant. Observe l'amplitude confortable et compare droite/gauche sans forcer.", technique: ["Commence par des transferts de poids légers.", "Explore progressivement l'extension du poignet sans rebond agressif.", "Répartis la pression sur toute la main, doigts compris.", "Augmente la durée et la charge au fil des séances plutôt que brutalement."], feel: ["Pression diffuse dans la paume.", "Avant-bras actifs.", "Étirement modéré et contrôlable au poignet."], avoid: ["Douleur vive ou pincement net.", "Forcer longtemps une amplitude qui s'aggrave.", "Passer directement de zéro appui à de longues séances de handstand."], advance: "Quand les appuis courts deviennent confortables et récupèrent bien, utilise-les dans le travail au mur.", next: { slug: "handstand-mur", label: "Apprendre le handstand au mur" } },
  "handstand-mur": { intro: "Le mur retire une partie du problème d'équilibre pour te laisser apprendre les appuis, la ligne et la sortie. Il doit devenir un outil, pas une béquille permanente.", objective: "Tenir une position inversée contrôlée et savoir en sortir calmement.", test: "Avant de monter, vérifie que tu peux supporter ton poids sur les mains et que l'espace autour de toi permet une sortie sûre.", technique: ["Commence avec une distance au mur qui te laisse monter sans choc.", "Pousse activement le sol avec les mains et garde les bras organisés.", "Rapproche progressivement le corps du mur seulement si tu gardes le contrôle.", "Apprends à redescendre volontairement avant de chercher de longues tenues."], feel: ["Forte pression dans les mains.", "Épaules actives pour pousser le sol.", "Tronc engagé pour limiter la cambrure excessive."], avoid: ["Monter sans savoir redescendre.", "Cogner systématiquement le mur avec les jambes.", "Continuer malgré une douleur croissante aux poignets ou aux épaules."], advance: "Quand la position au mur devient calme et que tu peux réduire brièvement le contact sans paniquer, commence le travail d'équilibre plus libre.", next: { slug: "handstand-debutant", label: "Construire ton handstand" } },
  "handstand-debutant": { intro: "Le handstand est une compétence : la force compte, mais l'équilibre se construit surtout par des expositions fréquentes et suffisamment propres pour apprendre quelque chose à chaque tentative.", objective: "Quitter progressivement le mur et trouver de courts instants d'équilibre contrôlé.", test: "Au mur, vérifie que tu peux entrer, tenir et sortir sans précipitation. Si toute ton attention sert encore à ne pas tomber, consolide d'abord cette étape.", technique: ["Travaille des tentatives courtes et fraîches plutôt que de lutter longtemps sous fatigue.", "Utilise les doigts et la paume pour corriger de petites variations d'équilibre.", "Cherche une ligne organisée sans exiger une perfection esthétique immédiate.", "Pratique une sortie sûre pour réduire la peur de dépasser le point d'équilibre."], feel: ["Les doigts corrigent finement l'équilibre.", "Les épaules restent actives.", "De brefs moments demandent moins d'effort que les tentatives désorganisées."], avoid: ["Multiplier les coups de pied de plus en plus forts.", "Rester systématiquement collé au mur sans apprendre à réduire le contact.", "Continuer quand les poignets ou épaules ne tolèrent plus la charge."], advance: "Mesure le progrès par la qualité des entrées, des sorties et des courts équilibres reproductibles, pas seulement par un record de secondes." },
};

function LearningCardPage({ slug }: { slug: string }) {
  const resource = v1Resources.find((item) => item.slug === slug)!;
  const card = cards[slug];
  return <article className="section shell narrow learningCard">
    <div className="eyebrow">{resource.kind} · {resource.hub}</div><h1>{resource.title}</h1><p className="lead">{card.intro}</p>
    <div className="learningMeta"><div><span>Objectif</span><strong>{card.objective}</strong></div><div><span>Capacité</span><strong>{resource.capability}</strong></div><div><span>Matériel</span><strong>{resource.equipment.length ? resource.equipment.join(", ") : "aucun matériel obligatoire"}</strong></div></div>
    <section className="articleSection"><div className="eyebrow">Test de départ</div><h2>Vérifie ton point de départ</h2><p>{card.test}</p></section>
    <section className="articleSection"><div className="eyebrow">Technique</div><h2>Les repères à garder</h2><ol className="contentList numberedList">{card.technique.map((item) => <li key={item}>{item}</li>)}</ol></section>
    <section className="articleSection sensationGrid"><div className="signalCard positiveSignal"><div className="eyebrow">Ce que tu dois ressentir</div><h2>Des signaux utiles</h2><ul>{card.feel.map((item) => <li key={item}>{item}</li>)}</ul></div><div className="signalCard cautionSignal"><div className="eyebrow">Ce que tu ne devrais pas ignorer</div><h2>Quand réduire la difficulté</h2><ul>{card.avoid.map((item) => <li key={item}>{item}</li>)}</ul><p>Une douleur vive ou persistante n'est pas un critère de progression. Arrête ou adapte l'exercice et demande un avis professionnel si nécessaire.</p></div></section>
    <section className="articleSection"><div className="eyebrow">Critère de passage</div><h2>Quand continuer ?</h2><p>{card.advance}</p></section>
    {(card.next || card.secondaryNext) && <section className="articleSection"><div className="eyebrow">Étape suivante</div><div className="nextGrid compactNextGrid">{card.next && <Link className="nextCard" href={`/bibliotheque/${card.next.slug}`}><strong>{card.next.label}</strong><span>Continuer →</span></Link>}{card.secondaryNext && <Link className="nextCard" href={`/bibliotheque/${card.secondaryNext.slug}`}><strong>{card.secondaryNext.label}</strong><span>Choisir cette branche →</span></Link>}</div></section>}
    <Link className="textLink" href={resource.hub === "tractions" ? "/tractions" : "/bibliotheque"}>← Retour au parcours</Link>
  </article>;
}

function FirstPullUpPage() {
  const steps = [["1", "Teste ta suspension", "Accroche-toi à une barre avec une prise confortable."], ["2", "Contrôle tes omoplates", "Apprends à initier le mouvement sans tout demander aux bras."], ["3", "Construis ton tirage horizontal", "Le rowing permet d'ajuster facilement la difficulté."], ["4", "Utilise l'assistance", "Aide-toi juste assez pour pratiquer le mouvement complet."], ["5", "Travaille la descente", "Les négatives développent le contrôle sur toute l'amplitude."], ["6", "Tente une répétition stricte", "Une répétition propre vaut mieux que plusieurs répétitions dégradées."]];
  return <article className="section shell narrow learningCard"><div className="eyebrow">Progression · partir de zéro</div><h1>Réussir sa première traction</h1><p className="lead">Identifie ce qui te manque aujourd'hui — prise, suspension, contrôle des épaules ou force de tirage — puis construis ces capacités une par une.</p><div className="learningMeta"><div><span>Objectif</span><strong>1 traction stricte</strong></div><div><span>Matériel</span><strong>Une barre</strong></div><div><span>Niveau</span><strong>Départ zéro</strong></div></div><section className="articleSection"><h2>La progression en 6 étapes</h2><ol className="progression detailedProgression">{steps.map(([number,title,text]) => <li className="progressionStep" key={number}><div className="stepNumber">{number.padStart(2,"0")}</div><div><h3>{title}</h3><p>{text}</p></div></li>)}</ol></section><section className="articleSection"><div className="eyebrow">Suite logique</div><div className="nextGrid"><Link className="nextCard" href="/bibliotheque/traction-technique"><strong>Technique de traction</strong><span>Affiner le mouvement →</span></Link><Link className="nextCard" href="/bibliotheque/10-tractions"><strong>De 1 à 10 tractions</strong><span>Construire le volume →</span></Link></div></section></article>;
}

export default async function ResourcePage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const resource = v1Resources.find((item) => item.slug === slug);
  if (!resource) notFound();
  if (slug === "premiere-traction") return <FirstPullUpPage />;
  if (cards[slug]) return <LearningCardPage slug={slug} />;
  return <article className="section shell narrow"><div className="eyebrow">{resource.kind} · {resource.level}</div><h1>{resource.title}</h1><p className="lead">{resource.summary}</p><div className="infoPanel"><p><strong>Capacité :</strong> {resource.capability}</p><p><strong>Matériel :</strong> {resource.equipment.length ? resource.equipment.join(", ") : "aucun matériel obligatoire"}</p></div><section className="articleSection"><h2>Ce que cette fiche doit t'apprendre</h2><p>Cette ressource est encore en cours d'enrichissement. Elle rejoindra le même modèle pédagogique : test de départ, technique, sensations, erreurs, progression et critères de passage.</p></section><Link className="textLink" href="/bibliotheque">← Retour à la bibliothèque</Link></article>;
}