import type { TrainingProgram } from "./types";

export const beginnerFoundationProgram: TrainingProgram = {
  id: "fondations-debutant-v1",
  label: "Fondations",
  audience: "Débutant qui veut construire une base avant de spécialiser ses objectifs.",
  frequencyPerWeek: 2,
  sessions: [
    {
      id: "fondations-a",
      label: "Séance A",
      goal: "Tirer, pousser, jambes et suspension.",
      exercises: [
        {
          resourceSlug: "rowing-incline",
          label: "Rowing incliné",
          sets: 2,
          min: 8,
          max: 12,
          unit: "reps",
          restSeconds: 120,
          effortCue: "Garde quelques répétitions possibles en réserve : les répétitions doivent rester propres.",
          progressionCue: "Quand 2 × 12 est propre sur deux séances, rends l'angle légèrement plus difficile.",
        },
        {
          resourceSlug: "pompes-inclinees",
          label: "Pompes inclinées",
          sets: 2,
          min: 8,
          max: 12,
          unit: "reps",
          restSeconds: 120,
          effortCue: "Choisis une hauteur qui laisse la dernière répétition contrôlée.",
          progressionCue: "Quand 2 × 12 est propre sur deux séances, baisse légèrement le support.",
        },
        {
          resourceSlug: "squat-poids-du-corps",
          label: "Squat",
          sets: 2,
          min: 8,
          max: 12,
          unit: "reps",
          restSeconds: 90,
          effortCue: "Utilise une amplitude que tu contrôles sans forcer une position douloureuse.",
          progressionCue: "Quand 2 × 12 est facile et stable, augmente progressivement l'amplitude ou la difficulté.",
        },
        {
          resourceSlug: "suspension-barre",
          label: "Suspension",
          sets: 2,
          min: 15,
          max: 30,
          unit: "seconds",
          restSeconds: 90,
          effortCue: "Arrête avant que la prise ou les épaules ne se désorganisent.",
          progressionCue: "Quand 2 × 30 s est confortable et reproductible, passe au contrôle scapulaire.",
        },
      ],
    },
    {
      id: "fondations-b",
      label: "Séance B",
      goal: "Contrôle des épaules, poussée, jambes et tirage.",
      exercises: [
        {
          resourceSlug: "controle-scapulaire",
          label: "Contrôle scapulaire",
          sets: 2,
          min: 6,
          max: 10,
          unit: "reps",
          restSeconds: 90,
          effortCue: "Le mouvement vient des omoplates, sans transformer l'exercice en petite traction.",
          progressionCue: "Quand 2 × 10 est propre et calme, conserve-le en préparation et donne plus de place au rowing.",
        },
        {
          resourceSlug: "pompes-inclinees",
          label: "Pompes inclinées",
          sets: 2,
          min: 8,
          max: 12,
          unit: "reps",
          restSeconds: 120,
          effortCue: "Reste sur une hauteur où le tronc et les épaules gardent la même organisation.",
          progressionCue: "Quand 2 × 12 est propre sur deux séances, baisse légèrement le support.",
        },
        {
          resourceSlug: "squat-poids-du-corps",
          label: "Squat",
          sets: 2,
          min: 8,
          max: 12,
          unit: "reps",
          restSeconds: 90,
          effortCue: "Répète la même amplitude avec contrôle plutôt que de chercher plus bas à tout prix.",
          progressionCue: "Quand 2 × 12 est stable, augmente progressivement l'amplitude ou la difficulté.",
        },
        {
          resourceSlug: "rowing-incline",
          label: "Rowing incliné",
          sets: 2,
          min: 8,
          max: 12,
          unit: "reps",
          restSeconds: 120,
          effortCue: "Termine la série avant que l'amplitude se raccourcisse nettement.",
          progressionCue: "Quand 2 × 12 est propre sur deux séances, rends l'angle légèrement plus difficile.",
        },
      ],
    },
  ],
  adaptationRule: "Ne change qu'une variable à la fois. Si la qualité baisse franchement, garde ou facilite la variante. Si la borne haute est reproductible sur deux séances, augmente légèrement la difficulté.",
  scopeNote: "Cette V1 valide la boucle séance → mesure → décision avec les capacités déjà documentées. Elle ne prétend pas encore couvrir tout le corps ni remplacer un programme individualisé.",
};
