import type { TrainingProgram } from "./types";

export const beginnerFoundationProgram: TrainingProgram = {
  id: "fondations-debutant-v1",
  label: "Fondations",
  audience: "Débutant qui veut construire une base avant de spécialiser ses objectifs.",
  frequencyPerWeek: 2,
  sessions: [
    {
      id: "fondations-a",
      label: "Séance A",
      goal: "Tirer, pousser, jambes et stabilité du tronc.",
      exercises: [
        {
          resourceSlug: "rowing-incline",
          label: "Rowing incliné",
          sets: 2,
          min: 8,
          max: 12,
          unit: "reps",
          restSeconds: 120,
          effortCue: "Garde quelques répétitions possibles en réserve : les répétitions doivent rester propres.",
          progressionCue: "Quand 2 × 12 est propre sur deux séances, rends l'angle légèrement plus difficile.",
        },
        {
          resourceSlug: "pompes-inclinees",
          label: "Pompes inclinées",
          sets: 2,
          min: 8,
          max: 12,
          unit: "reps",
          restSeconds: 120,
          effortCue: "Choisis une hauteur qui laisse la dernière répétition contrôlée.",
          progressionCue: "Quand 2 × 12 est propre sur deux séances, baisse légèrement le support.",
        },
        {
          resourceSlug: "squat-poids-du-corps",
          label: "Squat",
          sets: 2,
          min: 8,
          max: 12,
          unit: "reps",
          restSeconds: 90,
          effortCue: "Utilise une amplitude que tu contrôles sans forcer une position douloureuse.",
          progressionCue: "Quand 2 × 12 est facile et stable, augmente progressivement l'amplitude ou la difficulté.",
        },
        {
          resourceSlug: "gainage-debutant",
          label: "Gainage",
          sets: 2,
          min: 15,
          max: 30,
          unit: "seconds",
          restSeconds: 60,
          effortCue: "Garde une position que tu peux encore contrôler en respirant ; arrête avant de survivre au chrono.",
          progressionCue: "Quand 2 × 30 s reste calme sur deux séances, considère cette base comme disponible plutôt que d'allonger automatiquement le chrono.",
        },
      ],
    },
    {
      id: "fondations-b",
      label: "Séance B",
      goal: "Pousser, tirer, jambes et chaîne postérieure.",
      exercises: [
        {
          resourceSlug: "pompes-inclinees",
          label: "Pompes inclinées",
          sets: 2,
          min: 8,
          max: 12,
          unit: "reps",
          restSeconds: 120,
          effortCue: "Reste sur une hauteur où le tronc et les épaules gardent la même organisation.",
          progressionCue: "Quand 2 × 12 est propre sur deux séances, baisse légèrement le support.",
        },
        {
          resourceSlug: "rowing-incline",
          label: "Rowing incliné",
          sets: 2,
          min: 8,
          max: 12,
          unit: "reps",
          restSeconds: 120,
          effortCue: "Termine la série avant que l'amplitude se raccourcisse nettement.",
          progressionCue: "Quand 2 × 12 est propre sur deux séances, rends l'angle légèrement plus difficile.",
        },
        {
          resourceSlug: "squat-poids-du-corps",
          label: "Squat",
          sets: 2,
          min: 8,
          max: 12,
          unit: "reps",
          restSeconds: 90,
          effortCue: "Répète la même amplitude avec contrôle plutôt que de chercher plus bas à tout prix.",
          progressionCue: "Quand 2 × 12 est stable, augmente progressivement l'amplitude ou la difficulté.",
        },
        {
          resourceSlug: "pont-fessier-debutant",
          label: "Pont fessier",
          sets: 2,
          min: 8,
          max: 12,
          unit: "reps",
          restSeconds: 90,
          effortCue: "Monte et redescends avec la même amplitude sans chercher de hauteur en cambrant le bas du dos.",
          progressionCue: "Quand 2 × 12 reste contrôlé sur deux séances, garde cette base ; Calis n'invente pas encore de variante suivante.",
        },
      ],
    },
  ],
  adaptationRule: "Ne change qu'une variable à la fois. Si la qualité baisse franchement, garde ou facilite la variante. Si la borne haute est reproductible sur deux séances, augmente la difficulté seulement lorsqu'une progression documentée existe.",
  scopeNote: "Cette V1 couvre maintenant poussée, tirage, squat, stabilité du tronc et une première base de chaîne postérieure. Elle reste volontairement compacte et ne prétend pas encore couvrir toutes les capacités de la callisthénie ni remplacer un programme individualisé.",
};
